# Generated by Django 5.0.4 on 2024-04-07 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=50)),
                ('initial_funds', models.IntegerField()),
                ('funds_left', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_price', models.IntegerField()),
                ('final_price', models.IntegerField()),
                ('points', models.IntegerField()),
                ('sold_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.team')),
            ],
        ),
    ]
