# Generated by Django 5.0.4 on 2024-04-07 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='initial_funds',
        ),
    ]
