# Generated by Django 5.0.4 on 2024-04-07 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_remove_team_initial_funds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='final_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='sold_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.team'),
        ),
    ]
